\section{try... finally}

Bei Exceptions, die nicht abgefangen werden, sorgt \code{finally} für ein Ausführen des durch \textit{finally} eingeleiteten Anweisungsblock auch im Fall einer Exception\footnote{
    Java Language Specification - 14.20.2. Execution of try-finally and try-catch-finally : \url{https://docs.oracle.com/javase/specs/jls/se21/html/jls-14.html#jls-14.20.2} - abgerufen 26.01.2024
}, wie folgendes Beispiel zeigt:

\begin{minted}{java}
    public class TryCatchDemo {

        public String m1(boolean exc) {
            try {

                System.out.println("try 1.");

                if (exc) {
                    throw new Exception();
                }
                System.out.println("try 2.");

                return "foo";

            } catch (Exception e) {

                return "Exception.";

            } finally {
                return "finally.";
            }
        }

        public static void main(String[] args) {
           TryCatchDemo demo = new TryCatchDemo();
           System.out.println(demo.m1(false));
           System.out.println();
           System.out.println(demo.m1(true));
        }

    }
\end{minted}\\

\noindent
Die Ausgabe des Programms lautet:


\noindent
\begin{minted}[mathescape,
    numbersep=5pt,
    gobble=2,
    frame=none,
    framesep=2mm]{bash}
    try 1.
    try 2.
    finally.
    foo

    try 1.
    finally.
    Exception.
\end{minted}\\